import { prisma } from "../db";
import { notFound } from "../errors";
import { formatMoney } from "@/lib/commercial/calc";
import { COLORS, PAGE, columnXs, createDoc, header, parties, section, tableHeader, type Column } from "./doc";
import { ltr } from "./text";

/**
 * Contract document (PDF) generated from the stored contract (values copied from the accepted
 * quotation version). It is a working document for signature OUTSIDE the system — it makes
 * no claim of legal validity or electronic-signature compliance.
 */

const L = {
  ar: {
    title: "عقد تقديم خدمات",
    number: "رقم العقد",
    ref: "مرجع عرض السعر",
    start: "تاريخ البدء",
    end: "تاريخ الانتهاء",
    p1: "الطرف الأول (مقدم الخدمة)",
    p2: "الطرف الثاني (العميل)",
    vat: "الرقم الضريبي",
    value: "القيمة التعاقدية",
    subtotal: "المجموع الفرعي",
    discount: "الخصم",
    tax: "ضريبة القيمة المضافة",
    total: "إجمالي قيمة العقد",
    scope: "نطاق العمل",
    payment: "شروط الدفع",
    milestones: "المراحل التعاقدية",
    mTitle: "المرحلة",
    mDue: "الاستحقاق",
    mAmount: "المبلغ / النسبة",
    terms: "الشروط والأحكام",
    sign: "التوقيعات",
    s1: "عن الطرف الأول",
    s2: "عن الطرف الثاني",
    sLines: "الاسم: ____________________\nالتوقيع: __________________\nالتاريخ: __________________",
    disclaimer: "مستند صادر من نظام DMS للتشغيل لغرض التوقيع. التوقيع يتم خارج النظام، ولا يُعد هذا المستند توقيعاً إلكترونياً.",
    draft: "مسودة عقد",
    page: (p: number, n: number) => `صفحة ${p} من ${n}`
  },
  en: {
    title: "SERVICE AGREEMENT",
    number: "Contract no.",
    ref: "Quotation ref.",
    start: "Start date",
    end: "End date",
    p1: "Party one (provider)",
    p2: "Party two (client)",
    vat: "VAT no.",
    value: "Contract value",
    subtotal: "Subtotal",
    discount: "Discount",
    tax: "VAT",
    total: "Total contract value",
    scope: "Scope of work",
    payment: "Payment terms",
    milestones: "Milestones",
    mTitle: "Milestone",
    mDue: "Due",
    mAmount: "Amount / %",
    terms: "Terms & conditions",
    sign: "Signatures",
    s1: "For party one",
    s2: "For party two",
    sLines: "Name: ____________________\nSignature: _______________\nDate: ____________________",
    disclaimer: "Generated by DMS Business OS for signature. Signing happens outside the system; this document is not an electronic signature.",
    draft: "DRAFT CONTRACT",
    page: (p: number, n: number) => `Page ${p} of ${n}`
  }
};

const dateStr = (d: Date | null, lang: "ar" | "en") => (d ? new Intl.DateTimeFormat(lang === "ar" ? "ar-SA-u-nu-latn-ca-gregory" : "en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(d) : "—");

export async function renderContractPdf(organizationId: string, contractId: string) {
  const c = await prisma.contract.findFirst({
    where: { id: contractId, organizationId },
    include: { client: true, contact: true, quotation: { select: { number: true } }, quotationVersion: { select: { versionNumber: true, contentHash: true } }, milestones: { orderBy: { sortOrder: "asc" } } }
  });
  if (!c) throw notFound("Contract");
  const org = await prisma.organization.findUniqueOrThrow({ where: { id: organizationId } });
  const lang = c.language;
  const t = L[lang];
  const rtl = lang === "ar";
  const companyName = (rtl ? org.nameAr : null) ?? org.legalName ?? org.name;
  const d = createDoc({
    rtl,
    title: c.number,
    watermark: ["DRAFT", "INTERNAL_REVIEW"].includes(c.status) ? t.draft : null,
    footer: (p, n) => [companyName, ltr(c.number), t.page(p, n)].join("  ·  ")
  });
  header(d, t.title, [
    [t.number, c.number],
    [t.ref, c.quotation ? `${c.quotation.number} V${c.quotationVersion?.versionNumber ?? ""}` : "—"],
    [t.start, dateStr(c.startDate, lang)],
    [t.end, dateStr(c.endDate, lang)]
  ]);
  d.font("bold", 13, COLORS.ink);
  d.y = d.text(c.title, PAGE.m, d.y, d.cw) + 8;
  const contact = c.contact ? `${c.contact.firstName} ${c.contact.lastName ?? ""}`.trim() : "";
  parties(
    d,
    { title: t.p1, lines: [companyName, [org.address, org.city].filter(Boolean).join("، "), org.crNumber ? `CR ${ltr(org.crNumber)}` : "", org.vatNumber ? `${t.vat}: ${ltr(org.vatNumber)}` : ""] },
    { title: t.p2, lines: [c.client.displayName, contact, [c.client.address, c.client.city].filter(Boolean).join("، "), c.client.taxNumber ? `${t.vat}: ${c.client.taxNumber}` : ""] }
  );

  // value box
  const rows: [string, string][] = [
    [t.subtotal, formatMoney(c.subtotal.toFixed(2), lang, c.currency)],
    ...(c.discountTotal.gt(0) ? ([[t.discount, formatMoney(c.discountTotal.toFixed(2), lang, c.currency)]] as [string, string][]) : []),
    [t.tax, formatMoney(c.taxTotal.toFixed(2), lang, c.currency)],
    [t.total, formatMoney(c.contractValue.toFixed(2), lang, c.currency)]
  ];
  d.font("semibold", 9.5, COLORS.ink);
  d.y = d.text(t.value, PAGE.m, d.y, d.cw) + 2;
  rows.forEach(([k, v], i) => {
    const last = i === rows.length - 1;
    d.font(last ? "bold" : "regular", last ? 10.5 : 9, last ? COLORS.ink : COLORS.muted);
    d.text(k, PAGE.m, d.y, 260, { align: "start" });
    d.font(last ? "bold" : "semibold", last ? 10.5 : 9, COLORS.ink);
    d.y = d.text(v, PAGE.m + (rtl ? 0 : 0), d.y, d.cw, { align: "end" }) + 2;
  });
  d.y += 10;

  section(d, t.scope, c.scopeOfWork);
  section(d, t.payment, c.paymentTerms);

  if (c.milestones.length) {
    d.ensure(60);
    d.font("semibold", 9.5, COLORS.ink);
    d.y = d.text(t.milestones, PAGE.m, d.y, d.cw) + 4;
    const cols: Column[] = [
      { key: "t", title: t.mTitle, width: 295 },
      { key: "d", title: t.mDue, width: 110, align: "center" },
      { key: "a", title: t.mAmount, width: 110, align: "center" }
    ];
    const xs = columnXs(d, cols);
    tableHeader(d, cols);
    for (const m of c.milestones) {
      d.font("semibold", 9);
      const h = d.measure(m.title, cols[0].width - 8) + (m.description ? d.measure(m.description, cols[0].width - 8) : 0) + 8;
      d.ensure(h, () => tableHeader(d, cols));
      const y = d.y;
      d.font("semibold", 9, COLORS.ink);
      let yy = d.text(m.title, xs[0] + 4, y, cols[0].width - 8);
      if (m.description) {
        d.font("regular", 8, COLORS.muted);
        yy = d.text(m.description, xs[0] + 4, yy, cols[0].width - 8);
      }
      d.font("regular", 8.5, COLORS.ink);
      d.text(dateStr(m.dueDate, lang), xs[1] + 4, y, cols[1].width - 8, { align: "center" });
      d.text(m.amount ? formatMoney(m.amount.toFixed(2), lang, c.currency) : m.percentage ? `${m.percentage.toFixed(2)}%` : "—", xs[2] + 4, y, cols[2].width - 8, { align: "center" });
      d.y = Math.max(yy, y + 14) + 6;
      d.hr(d.y - 3);
    }
    d.y += 10;
  }
  section(d, t.terms, c.terms);

  // signatures
  d.ensure(130);
  d.font("semibold", 9.5, COLORS.ink);
  d.y = d.text(t.sign, PAGE.m, d.y, d.cw) + 6;
  const w = (d.cw - 24) / 2;
  const xs = rtl ? [PAGE.m + w + 24, PAGE.m] : [PAGE.m, PAGE.m + w + 24];
  let maxY = d.y;
  [t.s1, t.s2].forEach((title, i) => {
    d.font("semibold", 9, COLORS.ink);
    let y = d.text(title, xs[i], d.y, w);
    d.font("regular", 9, COLORS.muted);
    y = d.text(t.sLines, xs[i], y + 6, w, { lineGap: 8 });
    maxY = Math.max(maxY, y);
  });
  d.y = maxY + 12;
  d.font("regular", 7.5, COLORS.faint);
  d.y = d.text(t.disclaimer, PAGE.m, d.y, d.cw);

  const out = await d.finish();
  return { ...out, fileName: `${c.number}-${lang}.pdf` };
}
